package com.qubikore.assetsteward;

import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;
import io.swagger.v3.oas.annotations.security.SecurityScheme;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@SecurityScheme(
  name = "Bearer Authentication",
  type = SecuritySchemeType.HTTP,
  bearerFormat = "JWT",
  scheme = "bearer"
)
public class AssetStewardApplication {

    public static void main(String[] args) {
        SpringApplication.run(AssetStewardApplication.class, args);
    }

    @org.springframework.context.annotation.Bean
    public org.springframework.boot.CommandLineRunner dropOldConstraints(org.springframework.jdbc.core.JdbcTemplate jdbcTemplate) {
        return args -> {
            try {
                // Drop the old global unique constraints that were generated by Hibernate previously
                jdbcTemplate.execute("ALTER TABLE categories DROP CONSTRAINT IF EXISTS ukt8o6pivur7nn124jehx7cygw5");
                jdbcTemplate.execute("ALTER TABLE departments DROP CONSTRAINT IF EXISTS ukj6cwks7xecs5jov19ro8ge3qk");
                System.out.println("Old global unique constraints dropped successfully.");
            } catch (Exception e) {
                System.out.println("Note: Old constraints might not exist or couldn't be dropped: " + e.getMessage());
            }
        };
    }

}
